## Music Recommendation System (Machine Learning)

This project is aimed upon building a music recommendation system that gives the user recommendations on music based on his music taste by analysing his previously heard music and playlist. This project is done in two ways, using 'User - to - User Recommendation' and 'Item - to - Item Recommendation'. Birch, MiniBatchKMeans and KMeans algorithms are being used along with 'Surprise' module to compute the similarity between recommendations and user's already existing playlist for evaluation

### Obtaining Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
final = pd.read_csv('datasets/final/final.csv')
metadata = pd.read_csv('datasets/final/metadata.csv')

In [3]:
final.head()

,Unnamed: 0,track_id,acousticness,danceability,energy,instrumentalness,liveness,speechiness,tempo,valence,...,Holiday,Salsa,NuJazz,HipHop Beats,Modern Jazz,Turkish,Tango,Fado,Christmas,Instrumental
0,0,2,0.416675,0.675894,0.634476,0.010628,0.177647,0.159310,165.922,0.576661,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,3,0.374408,0.528643,0.817461,0.001851,0.105880,0.461818,126.957,0.269240,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,5,0.043567,0.745566,0.701470,0.000697,0.373143,0.124595,100.260,0.621661,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,10,0.951670,0.658179,0.924525,0.965427,0.115474,0.032985,111.562,0.963590,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,134,0.452217,0.513238,0.560410,0.019443,0.096567,0.525519,114.290,0.894072,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Model Selection - K Means Algorithm

In [4]:
from sklearn.cluster import KMeans
from sklearn.utils import shuffle

In [5]:
final = shuffle(final)

In [6]:
X = final.loc[[i for i in range(0, 6000)]]
Y = final.loc[[i for i in range(6000, final.shape[0])]]

In [7]:
X = shuffle(X)
Y = shuffle(Y)
X

,Unnamed: 0,track_id,acousticness,danceability,energy,instrumentalness,liveness,speechiness,tempo,valence,...,Holiday,Salsa,NuJazz,HipHop Beats,Modern Jazz,Turkish,Tango,Fado,Christmas,Instrumental
5170,5170,20343,0.899366,0.309087,0.857258,0.693016,0.176563,0.049786,160.004,0.506823,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
527,527,1324,0.990482,0.646492,0.152515,0.922513,0.108467,0.068214,102.557,0.178427,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2446,2446,10214,0.079600,0.621491,0.508696,0.737799,0.132724,0.037757,151.949,0.483805,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3470,3470,13794,0.870797,0.323307,0.724446,0.528357,0.122245,0.050288,112.562,0.638776,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2353,2353,9986,0.000418,0.362260,0.988963,0.546158,0.094108,0.071567,99.316,0.420166,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4531,4531,18002,0.995796,0.315272,0.108895,0.924637,0.109357,0.035137,145.933,0.376475,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3777,3777,14863,0.000850,0.763889,0.541350,0.932629,0.097046,0.105878,126.924,0.242432,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1502,1502,4414,0.623369,0.668185,0.546334,0.001415,0.103070,0.040425,120.918,0.860185,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3348,3348,13362,0.011568,0.666719,0.296587,0.868925,0.092343,0.101502,199.989,0.596082,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
328,328,843,0.462082,0.307545,0.725564,0.678784,0.123870,0.034770,134.439,0.062672,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
metadata.head()

   track_id           album_title artist_name   genre   track_title
0         2  AWOL - A Way Of Life        AWOL  HipHop          Food
1         3  AWOL - A Way Of Life        AWOL  HipHop  Electric Ave
2         5  AWOL - A Way Of Life        AWOL  HipHop    This World
3        10     Constant Hitmaker   Kurt Vile     Pop       Freeway
4       134  AWOL - A Way Of Life        AWOL  HipHop  Street Music

In [9]:
metadata = metadata.set_index('track_id')

In [10]:
#X.drop(['label'], axis= 1, inplace= True)

In [11]:
X.columns

Index(['Unnamed: 0', 'track_id', 'acousticness', 'danceability', 'energy',
       'instrumentalness', 'liveness', 'speechiness', 'tempo', 'valence',
       ...
       'Holiday', 'Salsa', 'NuJazz', 'HipHop Beats', 'Modern Jazz', 'Turkish',
       'Tango', 'Fado', 'Christmas', 'Instrumental'],
      dtype='object', length=930)

In [12]:
kmeans = KMeans(n_clusters=6)

In [13]:
Y.head()

,Unnamed: 0,track_id,acousticness,danceability,energy,instrumentalness,liveness,speechiness,tempo,valence,...,Holiday,Salsa,NuJazz,HipHop Beats,Modern Jazz,Turkish,Tango,Fado,Christmas,Instrumental
8934,8934,40021,0.912952,0.172509,0.483039,9.606068e-01,0.121310,0.038527,70.010,0.212790,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11296,11296,62648,0.002752,0.459962,0.848277,4.351599e-01,0.223938,0.059655,150.054,0.208182,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11658,11658,71365,0.008194,0.307737,0.865938,1.460000e-08,0.132677,0.045133,142.781,0.450539,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6918,6918,29840,0.000090,0.162364,0.385605,8.667696e-01,0.152959,0.057952,124.191,0.510732,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10407,10407,48290,0.781594,0.725792,0.888282,7.428689e-01,0.104560,0.041871,124.958,0.417743,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
def fit(df, algo, flag=0):
    if flag:
        algo.fit(df)
    else:
         algo.partial_fit(df)          
    df['label'] = algo.labels_
    return (df, algo)

In [15]:
def predict(t, Y):
    y_pred = t[1].predict(Y)
    mode = pd.Series(y_pred).mode()
    return t[0][t[0]['label'] == mode.loc[0]]

In [16]:
def recommend(recommendations, meta, Y):
    dat = []
    for i in Y['track_id']:
        dat.append(i)
    genre_mode = meta.loc[dat]['genre'].mode()
    artist_mode = meta.loc[dat]['artist_name'].mode()
    return meta[meta['genre'] == genre_mode.iloc[0]], meta[meta['artist_name'] == artist_mode.iloc[0]], meta.loc[recommendations['track_id']]

In [17]:
t = fit(X, kmeans, 1)

In [18]:
recommendations = predict(t, Y)

In [19]:
output = recommend(recommendations, metadata, Y)

In [20]:
genre_recommend, artist_name_recommend, mixed_recommend = output[0], output[1], output[2]

In [21]:
genre_recommend.shape

(3892, 4)

In [22]:
artist_name_recommend.shape

(52, 4)

In [23]:
mixed_recommend.shape

(1189, 4)

In [24]:
# Genre wise recommendations
genre_recommend.head()

              album_title     artist_name genre                 track_title
track_id
153        Arc and Sender  Arc and Sender  Rock          Hundred-Year Flood
154        Arc and Sender  Arc and Sender  Rock         Squares And Circles
155       unreleased demo  Arc and Sender  Rock     Maps of the Stars Homes
169          Boss of Goth      Argumentix  Rock                Boss of Goth
170          Nightmarcher      Argumentix  Rock  Industry Standard Massacre

In [25]:
# Artist wise recommendations
artist_name_recommend.head()

,album_title,artist_name,genre,track_title
track_id,,,,
34660,Zehu,51%,AvantGarde|International|Blues|Jazz|,Hadri Ha'Kat
34661,Zehu,51%,AvantGarde|International|Blues|Jazz|,Blender Tzivoni
34662,Zehu,51%,AvantGarde|International|Blues|Jazz|,Naniah
34663,Zehu,51%,AvantGarde|International|Blues|Jazz|,Yoter Miday
34664,Zehu,51%,AvantGarde|International|Blues|Jazz|,"Yamim, Lielot"

In [26]:
# Mixed Recommendations
mixed_recommend.head()

,album_title,artist_name,genre,track_title
track_id,,,,
9986,50FOOTWAVE,50 Foot Wave,Rock,Clara Bow
18781,La Maquina Olvidada,Rebe,Rock,Catrionas 5th Dream
6753,Walrus Prison,James Amoeba,Electronic,tube dwellers unlubricated
13201,netBloc Vol. 10: Postmodernism is dead. Postmi...,Ghostown,HipHop,Moy Moy Moy
21898,Neuro Science EP,B1t Crunch3r vs Killeralien vs Phonetic System,Electronic,White Hole Nocturne feat. Jay Cotton

In [27]:
recommendations.head()

,Unnamed: 0,track_id,acousticness,danceability,energy,instrumentalness,liveness,speechiness,tempo,valence,...,Salsa,NuJazz,HipHop Beats,Modern Jazz,Turkish,Tango,Fado,Christmas,Instrumental,label
2353,2353,9986,0.000418,0.362260,0.988963,0.546158,0.094108,0.071567,99.316,0.420166,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
4727,4727,18781,0.983296,0.394027,0.033288,0.939440,0.145404,0.050072,143.475,0.280015,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
1989,1989,6753,0.010156,0.431723,0.786315,0.019103,0.100047,0.787266,171.239,0.053847,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
3321,3321,13201,0.252772,0.650640,0.379765,0.558373,0.087998,0.124143,196.093,0.396997,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
5483,5483,21898,0.007328,0.781604,0.937258,0.800969,0.257750,0.077552,140.087,0.865400,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3

In [28]:
artist_name_recommend['artist_name'].value_counts()

artist_name
51%    52
Name: count, dtype: int64

In [29]:
genre_recommend['genre'].value_counts()

genre
Rock    3892
Name: count, dtype: int64

In [30]:
genre_recommend['artist_name'].value_counts()

artist_name
Glove Compartment               65
Blah Blah Blah                  62
Mors Ontologica                 50
Les Baudouins Morts             38
Kraus                           35
                                ..
Alone in 1982                    1
Ostrich Tuning                   1
The Dalai Lama Rama Fa Fa Fa     1
The Rusty Bells                  1
Lost Boy                         1
Name: count, Length: 725, dtype: int64

#### Testing

In [31]:
testing = Y.iloc[6:12]['track_id']

In [32]:
testing

12405     99703
8440      37146
10984     52931
12434    101109
9388      41980
12067     86373
Name: track_id, dtype: int64

In [33]:
ids = testing.loc[testing.index]

In [34]:
songs = metadata.loc[testing.loc[list(testing.index)]]

In [35]:
songs

,album_title,artist_name,genre,track_title
track_id,,,,
99703,[EPV_152] HEAVEN,eden,Electronic,HEAVEN
37146,True Old School Horror Grind,Zombie Raiders,Rock,The Dead Live!
52931,Just Had To Let You Know,Lorenzo's Music,AvantGarde|International|Blues|,Roulette
101109,Live on WFMU's Airborne Event with Dan Bodah -...,Speed The Plough,Rock,Perfect North
41980,Voy a Explotar Soundtrack,Jessy Bulbo,AvantGarde|International|Blues|,No escuches a tus idolos
86373,Live on WFMU's Airborne Event with Dan Bodah -...,Bliss Blood & Al Street,AvantGarde|International|,Liplock

In [36]:
re = predict(t, Y.iloc[6:12])

In [37]:
output = recommend(re, metadata, Y.iloc[6:12])

In [38]:
ge_re, ge_ar, ge_mix = output[0], output[1], output[2]

In [39]:
ge_re.head()

,album_title,artist_name,genre,track_title
track_id,,,,
1574,Please Throw Me Back in The Ocean,Sir Lord Von Raven,AvantGarde|International|Blues|,The Glass Castle
1575,Please Throw Me Back in The Ocean,Sir Lord Von Raven,AvantGarde|International|Blues|,Take it or Leave it
1892,Tommy Jay's Tall Tales Of Trauma,Tommy Jay,AvantGarde|International|Blues|,I Was There
3394,Live at WFMU on Liz Berg's Show on 5/19/2008,Bonde Do Role,AvantGarde|International|Blues|,Gasolina / Contamida
3396,Live at WFMU on Liz Berg's Show on 5/19/2008,Bonde Do Role,AvantGarde|International|Blues|,Solta o Franco

In [40]:
ge_ar.head(10)

,album_title,artist_name,genre,track_title
track_id,,,,
86373,Live on WFMU's Airborne Event with Dan Bodah -...,Bliss Blood & Al Street,AvantGarde|International|,Liplock
86381,Live on WFMU's Airborne Event with Dan Bodah -...,Bliss Blood & Al Street,AvantGarde|International|,Swallow The Dice
86382,Live on WFMU's Airborne Event with Dan Bodah -...,Bliss Blood & Al Street,AvantGarde|International|,Bulletproof

In [41]:
ge_mix.head(10)

,album_title,artist_name,genre,track_title
track_id,,,,
9986,50FOOTWAVE,50 Foot Wave,Rock,Clara Bow
18781,La Maquina Olvidada,Rebe,Rock,Catrionas 5th Dream
6753,Walrus Prison,James Amoeba,Electronic,tube dwellers unlubricated
13201,netBloc Vol. 10: Postmodernism is dead. Postmi...,Ghostown,HipHop,Moy Moy Moy
21898,Neuro Science EP,B1t Crunch3r vs Killeralien vs Phonetic System,Electronic,White Hole Nocturne feat. Jay Cotton
24314,Live at Jetto Festival,Daan Hendriks,AvantGarde|International|,Benin Cut-throats
23548,Le Disque d'Or des Baudouins Morts,Les Baudouins Morts,Rock,Credo
23556,Le Disque d'Or des Baudouins Morts,Les Baudouins Morts,Rock,Perkhof
17603,Born Bad,Wooden Wand,Rock,Bad Form/American Cream
15484,Live Recordings by the Baltimore Taper,AK Slaughter,HipHop,Tickle This Would Ya?

In [42]:
ge_re.shape

(1507, 4)

In [43]:
ge_ar.shape

(3, 4)

In [44]:
ge_mix.shape

(1189, 4)

### Model Selection - MiniBatchKMeans

In [45]:
from sklearn.cluster import MiniBatchKMeans

In [46]:
mini = MiniBatchKMeans(n_clusters = 6)

In [47]:
X.drop('label', axis=1, inplace=True)

In [48]:
# Let's divide the intital dataset into pieces to demonstrate online learning
part_1, part_2, part_3 = X.iloc[0: 2000], X.iloc[2000:4000], X.iloc[4000:6000]

In [49]:
for i in [part_1, part_2, part_3]:
    t = fit(i, mini)
    mini = t[1]
    i = t[0]

C:\Users\User\AppData\Local\Temp\ipykernel_18220\669684851.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = algo.labels_
C:\Users\User\AppData\Local\Temp\ipykernel_18220\669684851.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = algo.labels_
C:\Users\User\AppData\Local\Temp\ipykernel_18220\669684851.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = algo.labels_

In [50]:
X = pd.concat([part_1, part_2, part_3])

In [51]:
X.columns

Index(['Unnamed: 0', 'track_id', 'acousticness', 'danceability', 'energy',
       'instrumentalness', 'liveness', 'speechiness', 'tempo', 'valence',
       ...
       'Salsa', 'NuJazz', 'HipHop Beats', 'Modern Jazz', 'Turkish', 'Tango',
       'Fado', 'Christmas', 'Instrumental', 'label'],
      dtype='object', length=931)

In [52]:
X.head(3)

,Unnamed: 0,track_id,acousticness,danceability,energy,instrumentalness,liveness,speechiness,tempo,valence,...,Salsa,NuJazz,HipHop Beats,Modern Jazz,Turkish,Tango,Fado,Christmas,Instrumental,label
5170,5170,20343,0.899366,0.309087,0.857258,0.693016,0.176563,0.049786,160.004,0.506823,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
527,527,1324,0.990482,0.646492,0.152515,0.922513,0.108467,0.068214,102.557,0.178427,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
2446,2446,10214,0.079600,0.621491,0.508696,0.737799,0.132724,0.037757,151.949,0.483805,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5

In [53]:
X['label'].value_counts()

label
2    2833
1    1161
5    1138
3     597
4     137
0     134
Name: count, dtype: int64

In [54]:
recommendations = predict((X, mini), Y)

In [55]:
output = recommend(recommendations, metadata, Y)

In [56]:
genre_recommend_mini, artist_name_recommend_mini, mixed_mini = output[0], output[1], output[2]

In [57]:
genre_recommend_mini.shape

(3892, 4)

In [58]:
artist_name_recommend_mini.shape

(52, 4)

In [59]:
# Genre wise recommendations
genre_recommend_mini.head()

              album_title     artist_name genre                 track_title
track_id
153        Arc and Sender  Arc and Sender  Rock          Hundred-Year Flood
154        Arc and Sender  Arc and Sender  Rock         Squares And Circles
155       unreleased demo  Arc and Sender  Rock     Maps of the Stars Homes
169          Boss of Goth      Argumentix  Rock                Boss of Goth
170          Nightmarcher      Argumentix  Rock  Industry Standard Massacre

In [60]:
# Artist wise recommendations
artist_name_recommend_mini.head()

,album_title,artist_name,genre,track_title
track_id,,,,
34660,Zehu,51%,AvantGarde|International|Blues|Jazz|,Hadri Ha'Kat
34661,Zehu,51%,AvantGarde|International|Blues|Jazz|,Blender Tzivoni
34662,Zehu,51%,AvantGarde|International|Blues|Jazz|,Naniah
34663,Zehu,51%,AvantGarde|International|Blues|Jazz|,Yoter Miday
34664,Zehu,51%,AvantGarde|International|Blues|Jazz|,"Yamim, Lielot"

In [61]:
# Mixed Recommendations
mixed_mini.head()

,album_title,artist_name,genre,track_title
track_id,,,,
9986,50FOOTWAVE,50 Foot Wave,Rock,Clara Bow
18781,La Maquina Olvidada,Rebe,Rock,Catrionas 5th Dream
6753,Walrus Prison,James Amoeba,Electronic,tube dwellers unlubricated
13201,netBloc Vol. 10: Postmodernism is dead. Postmi...,Ghostown,HipHop,Moy Moy Moy
21898,Neuro Science EP,B1t Crunch3r vs Killeralien vs Phonetic System,Electronic,White Hole Nocturne feat. Jay Cotton

### Model Selection - Birch

In [62]:
from sklearn.cluster import Birch

In [63]:
birch = Birch(n_clusters = 6)

In [64]:
X.drop('label', axis=1, inplace=True)

In [65]:
# Let's divide the intital dataset into pieces to demonstrate online learning
part_1, part_2, part_3 = X.iloc[0: 2000], X.iloc[2000:4000], X.iloc[4000:6000]

In [66]:
for i in [part_1, part_2, part_3]:
    t = fit(i, birch)
    mini = t[1]
    i = t[0]

C:\Users\User\AppData\Local\Temp\ipykernel_18220\669684851.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = algo.labels_
C:\Users\User\AppData\Local\Temp\ipykernel_18220\669684851.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = algo.labels_
C:\Users\User\AppData\Local\Temp\ipykernel_18220\669684851.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label'] = algo.labels_

In [67]:
X = pd.concat([part_1, part_2, part_3])

In [68]:
X.columns

Index(['Unnamed: 0', 'track_id', 'acousticness', 'danceability', 'energy',
       'instrumentalness', 'liveness', 'speechiness', 'tempo', 'valence',
       ...
       'Salsa', 'NuJazz', 'HipHop Beats', 'Modern Jazz', 'Turkish', 'Tango',
       'Fado', 'Christmas', 'Instrumental', 'label'],
      dtype='object', length=931)

In [69]:
X.head(3)

,Unnamed: 0,track_id,acousticness,danceability,energy,instrumentalness,liveness,speechiness,tempo,valence,...,Salsa,NuJazz,HipHop Beats,Modern Jazz,Turkish,Tango,Fado,Christmas,Instrumental,label
5170,5170,20343,0.899366,0.309087,0.857258,0.693016,0.176563,0.049786,160.004,0.506823,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
527,527,1324,0.990482,0.646492,0.152515,0.922513,0.108467,0.068214,102.557,0.178427,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
2446,2446,10214,0.079600,0.621491,0.508696,0.737799,0.132724,0.037757,151.949,0.483805,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4

In [70]:
X['label'].value_counts()

label
3    1345
1    1317
2    1034
4     895
5     761
0     648
Name: count, dtype: int64

In [71]:
recommendations = predict((X, birch), Y)

In [72]:
output = recommend(recommendations, metadata, Y)

In [73]:
genre_recommend_birch, artist_name_recommend_birch, mixed_birch = output[0], output[1], output[2]

In [74]:
genre_recommend_birch.shape

(3892, 4)

In [75]:
artist_name_recommend_birch.shape

(52, 4)

In [76]:
# Genre wise recommendations
genre_recommend_birch.head()

              album_title     artist_name genre                 track_title
track_id
153        Arc and Sender  Arc and Sender  Rock          Hundred-Year Flood
154        Arc and Sender  Arc and Sender  Rock         Squares And Circles
155       unreleased demo  Arc and Sender  Rock     Maps of the Stars Homes
169          Boss of Goth      Argumentix  Rock                Boss of Goth
170          Nightmarcher      Argumentix  Rock  Industry Standard Massacre

In [77]:
# Artist wise recommendations
artist_name_recommend_birch.head()

,album_title,artist_name,genre,track_title
track_id,,,,
34660,Zehu,51%,AvantGarde|International|Blues|Jazz|,Hadri Ha'Kat
34661,Zehu,51%,AvantGarde|International|Blues|Jazz|,Blender Tzivoni
34662,Zehu,51%,AvantGarde|International|Blues|Jazz|,Naniah
34663,Zehu,51%,AvantGarde|International|Blues|Jazz|,Yoter Miday
34664,Zehu,51%,AvantGarde|International|Blues|Jazz|,"Yamim, Lielot"

In [78]:
# Mixed Recommendations
mixed_birch.head()

,album_title,artist_name,genre,track_title
track_id,,,,
20343,Live at WFMU on Cherry Blossom Clinic with Ter...,Lover!,Rock,Ronny
1324,Blissful Lethargy,Nicky Andrews,Electronic,Flacidity
13794,Live at WFMU on Pat Duncan's Show 4/23/09,Ism,Rock,Nixon Now More Than Ever
17821,WFMU live broadcast from Barbes on Transpacifi...,Scott Kettner's Brazilian Brass Band,AvantGarde|International|,Title Unknown
20935,Live at WFMU on Irene Trudel's Show 11/9/2009,Hopewell,Rock,"10,000 Black Masses / Realms of Gold Outro / W..."